spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    "password": ${DATASOURCE_PASSWORD}
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: ${MAIL_SMTP_HOST}
    port: 465
    protocol: "smtps"
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}
    from: ${MAIL_FROM}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
jwt:
  signing-key: ${JWT_SINGING_KEY}
  issuer: ${JWT_ISSUER}
otp:
  length: 6
  expiration-time-in-hours: 24
  valid-characters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
server:
  port: ${SERVER_PORT:8080}