name: Build, test and deploy docker image to Y.Cloud Container Registry
on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: auth-server

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
    - name: Login to Y.Cloud Container Registry
      env: 
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      run: echo "${REGISTRY_TOKEN}" | docker login cr.yandex -u json_key --password-stdin
    - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
      run: ./gradlew bootBuildImage --imageName=$IMAGE_NAME
    - name: Tag & publish to Container Registry
      env: 
        CONTAINER_REGISTRY_ID: ${{ secrets.CONTAINER_REGISTRY_ID }}
      run: |
        IMAGE_ID=cr.yandex/${CONTAINER_REGISTRY_ID}/$IMAGE_NAME
        VERSION=latest
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
